Local run
basler/hucon pull request #40
Opened 2020-09-18 13:17 UTC by SaschaMzH

When the server is started locally, the python lib will be extended to the python path. This will make it possible to run the entire project locally to debug.

2020-10-02 11:29 UTC, SaschaMzH commented
@HeavyKid @JonasTrampe @toklinke Who can do the review?

2020-10-16 11:46 UTC, toklinke requested changes

2020-10-16 11:46 UTC, toklinke commented on start_server.sh
> +OMEGA=$( uname -a | grep Omega )
The script will terminate here, if the output of `uname -a` does not contain "Omega".
The reason for this is the exit status of grep, see `man grep`:

> Normally the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.

So, grep will return 1 which will make the exit status of the whole piped command to be 1. Because we invoke sh with `-e`, the script will terminate here.

2020-10-16 11:46 UTC, toklinke commented on start_server.sh
> +OMEGA=$( uname -a | grep Omega )
We could use the exit status of grep directly. So we do not need to check whether the captured output is empty.

2020-10-16 13:51 UTC, SaschaMzH commented on start_server.sh
> +OMEGA=$( uname -a | grep Omega )
The new commit will fix that. Thanks.

2020-10-19 09:12 UTC, toklinke approved these changes

2020-10-19 09:13 UTC, toklinke commented on start_server.sh
> +OMEGA=$( uname -a | grep Omega )
Using `grep -c` is also a good idea. :+1:

2020-10-19 11:11 UTC, merged