Getting started
basler/hucon pull request #42
Opened 2020-12-21 13:53 UTC by SaschaMzH

Now the getting started documentation is complete.

2021-01-07 12:07 UTC, JonasTrampe requested changes
Bitte anpassen

2021-01-07 12:07 UTC, JonasTrampe commented on docs/de/getting_started/python.md
> +Unter diesem Menüpunkt findest du alles im dein Programm zu laden oder zu speichern. Wenn du einfach mal ein neues Programm erstellen möchtest wirst du auch in diesem Menü fündig.
möchtest**,** wirst

2021-01-07 12:07 UTC, JonasTrampe commented on docs/de/getting_started/python.md
> +Du kannst mit den Ereignis-Funktionen eigene Software Knöpfe erstellen. Die knöpfe funktionieren dann ähnlich wie eine virtuelle Fernbedienung. Klick einfach auf **Buttons** um die virtuelle Fernbedi
. Die **K**nöpfe funktionieren

2021-01-07 12:07 UTC, JonasTrampe commented on docs/de/getting_started/python.md
> +Dein code kannst du direkt hier hinein schreiben. Wenn du auf den **Start** Knopf klickst wird der gesamte code auf deinen HuCon übertragen und dort ausgeführt.
**C**ode (2 mal)

2021-01-07 12:07 UTC, JonasTrampe commented on docs/en/getting_started/python.md
> +Your HuCon uses python internally to be able to be programmed. So if you want to get the maximum out of your robot, just use the programming language [python](https://www.python.org/). On the interne
**P**ython (2 mal)

2021-01-07 12:07 UTC, JonasTrampe commented on docs/en/getting_started/python.md
> +To program your HuCon directly in python you just have to click on the **editor** tile on the start page.
**P**ython

2021-01-07 18:59 UTC, toklinke requested changes
Only some small issues, otherwise good job!

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Blockly ist eine hervoragende Möglichkeit das Programmieren zu erlernen. Dabei werden einfache Blöcke miteinander verbunden um einen Ablauf des Programms darzustellen.
Komma nach "Möglichkeit".
Komma vor "um".

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Um deinen HuCon mit den Blockly Blöcken zu programmieren muss du lediglich auf die **Blockly** kachel auf der Startseite klicken.
muss**t**

Komma nach "programmieren"

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Falls du nicht weißt wie du beginnen sollst, dann schau dir einfach die mitgelieferten Beispiele an. Du kannst alle Beispiele öffnen und unter einem neuen Namen speichern wenn du diese verändert hast
Komma nach "weißt"

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Das Hauptmenü hat einige Unter-Menüs um deinen Arbeitsbereich zu laden/speichern oder dein Programm zu starten/stoppen. Zusätzlich kann über das Menü der Code oder die Log-Ausgabe ein- beziehungsweis
Ich finde die Formulierung mit "um" hier unschön.
Wie wäre es hiermit?

Das Hauptmenü hat einige Unter-Menüs zum Laden/Speichern deines Arbeitsbereichs und zum Starten/Stoppen deines Programms.

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Auf der linken Seite findest du ein Menü mit vielen Blöcken die dir zum Programmieren zu verfügung stehen. Einige sind dabei von uns entwickelt worden die anderen kommen von google.
Ich persönlich würde den zweiten Satz auch streichen.

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Auf der linken Seite findest du ein Menü mit vielen Blöcken die dir zum Programmieren zu verfügung stehen. Einige sind dabei von uns entwickelt worden die anderen kommen von google.
Komma nach "Blöcken"

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Auf der Arbeitsfläche entsteht dein Programm. Verbinde einfach ein par Blöcke miteinander und starte dein Programm um zu sehen was passiert.
Wir liefern doch ein paar Beispiele mit. Vielleicht sollte man hier auf diese verweisen. Nach dem Motto "gucke dir die Beispiele an, um zu sehen, wie Blöcke miteinander kombiniert werden können.

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Dein Programm auf der Arbeitsfläche wird in Code umgesetzt, welcher dann auf deinem HuCon ausgeführt wird. Wenn du sehen möchtest was die Blöcke für einen Code erzeugen, dann blende dir diesen Bereic
Ich finde den Vorschlag gut.

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Der HuCon gibt dir einen Hinweis wenn dein Programm ein Fehler enthält. Diese Hinweise siehst du dann in der Log-Ausgabe. Zusätzlich kannst du selber Ausgaben auf der Log-Ausgabe mit der *gib aus*-Fu
Komma vor "wenn"
"ein**en** Fehler"

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/initial_setup.md
> +Nach dem zweiten Befehl wird eine Menge an Text auf der Konsole ausgegeben und dein HuCon während dieses Vorgangs einmal neu gestartet. Dieser Vorgang kann bis zu 5 Minuten dauern, bis dein HuCon wie
Ich würde hier noch ein "wird" einfügen:

"... und dein HuCon **wird** während ..."

Das liest sich dann besser, weil das "wird" aus dem ersten Teilsatz so weit weg ist.

Den letzten Satz würde ich kürzer fassen und die Wiederholung von "dieser Vorgang" vermeiden:
"Es kann bis zu 5 Minuten dauern, bis dein HuCon wieder betriebsbereit ist."

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/initial_setup.md
> +    Bitte achte darauf, dass dein HuCon nicht von deinem vom Computer getrennt wird. Sonst könnte es sein, dass er danach kaputt ist.
"vom" ist zu viel.

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/initial_setup.md
> +   `wget https://github.com/basler_hucon/releases/download/[VERSION]/hucon-[VERSION].run -O hucon.run`
Sollte man hier noch einen Link einfügen, wo man die aktuelle Version rausfindet?

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/initial_setup.md
> +Zum schluss solltest du deinen HuCon mit dem befehl `reboot` neu starten.
"**S**chluss" und "**B**efehl" beide mit großem "S".

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/python.md
> +## Hauptmenü
Ab hier gelten die gleichen Anmerkungen wie in `getting_started/blockly.md`, bitte kurz vergleichen und ggf. mitanpassen.

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/update.md
> +Verbinde den HuCon mit einem Netzteil oder einer Baterie und warte bis die Augen grün aufgeleuchtet haben.
"Bat**t**erie"
Komma nach "warte".

Was ich mich gerade frage: Was genau meinst du mit Batterie? Eher so etwas wie eine Powerbank, die man dann an den MicroUSB-Port hängt, oder?

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/update.md
> +Danach öffnest du deinen Browser und gehst auf die Startseite des HuCon. Dort findest du den Menüpunkt **Einstellung** und daunter den Punkt **Aktualiseren**.
"da**r**unter"
"Aktualis**i**eren"

2021-01-07 18:59 UTC, toklinke commented on docs/de/getting_started/update.md
> +Das aktualisieren kann mehrer minuten Dauern und während des gesammten Prozesses wird er sich einmal neu starten. Anschließend ist er wieder betriebsbereit.
"mehrer**e**"
"**M**inuten"
"**d**auern"
"gesamten"

"er" durch "dein HuCon" ersetzen

2021-01-07 18:59 UTC, toklinke commented on docs/en/getting_started/blockly.md
> +Under this menu item you will find everything you need to load or save your program. If you simply want to create a new program, you will also find it in this menu.
What is "it" in "you will also find it"?

Maybe replace the last sentence by something like the following:
"If you simply want to create a new program, you can also use this menu."

2021-01-07 18:59 UTC, toklinke commented on docs/en/getting_started/blockly.md
> +On the left side you will find a menu with many blocks that you can use for programming. Some of them are developed by us, the others come from google.
Same as for German: Delete the last sentence.

2021-01-07 18:59 UTC, toklinke commented on docs/en/getting_started/initial_setup.md
> +   `wget https://github.com/basler_hucon/releases/download/[VERSION]/hucon-[VERSION].run -O hucon.run`.
Same as for German version: Provide link that can be used to find out current version?

2021-01-07 18:59 UTC, toklinke commented on docs/en/getting_started/update.md
> +Connect the HuCon to a power supply or a battery and wait until the eyes are green.
Same as for German: What exactly is meant by "battery"?

2021-01-07 18:59 UTC, toklinke commented on docs/en/getting_started/update.md
> +The update can take several minutes and during the whole process it will reboot once. Afterwards it is ready for operation again.
Same as for German: "...during the whole process **the HuCon** will reboot..."

2021-01-07 18:59 UTC, toklinke commented on docs_config.json
> +            "getting_started": "erste Schritte",
"Erste" mit großem "E", da es sich um eine Überschrift handelt, oder nicht?

2021-01-07 19:11 UTC, JonasTrampe commented on docs/de/getting_started/blockly.md
> +Blockly ist eine hervoragende Möglichkeit das Programmieren zu erlernen. Dabei werden einfache Blöcke miteinander verbunden um einen Ablauf des Programms darzustellen.
Da sollte kein Komma nach Möglichkeit kommen, ist kein eingeschobener Halbsatz mit eigenem Verb.

2021-01-07 19:14 UTC, JonasTrampe commented
Mhhh magst du die Änderungen Squashen? Ansonsten wird die Rückverfolgbarkeit schwierig, wenn man auf den Commits gearbeitet hat - TFS macht hier wirklich einen besseren Job )=

2021-01-08 12:57 UTC, SaschaMzH commented on docs/de/getting_started/update.md
> +Verbinde den HuCon mit einem Netzteil oder einer Baterie und warte bis die Augen grün aufgeleuchtet haben.
Ja, ich meine ein PowerBank

2021-01-08 13:18 UTC, SaschaMzH commented
So, Änderungen übernommen und mit den vorherigen zusammen gefügt.

2021-01-14 09:48 UTC, JonasTrampe commented on docs/de/getting_started/blockly.md
> +Du kannst mit den Ereignis-Blöcken eigene Software Knöpfe erstellen. Die knöpfe funktionieren dann ähnlich wie eine virtuelle Fernbedienung. Klick einfach auf **Buttons** um die virtuelle Fernbedienu
Progemm -> Programm

2021-01-15 13:30 UTC, SaschaMzH commented on docs/de/getting_started/initial_setup.md
> +   `wget https://github.com/basler_hucon/releases/download/[VERSION]/hucon-[VERSION].run -O hucon.run`
Das könnte nur funktionieren wenn man ein **latest** tag verwendet oder?

2021-01-15 13:40 UTC, SaschaMzH commented
Vielen Dank für eure Anmerkungen. Ich habe nun alle Anmerkungen nochmal geprüft und wenn ich sie übernommen habe auch hier bei git auf resolve gestellt.
Es wäre klasse wenn ihr noch mal über den letzten Punkt schauen könntet.

2021-01-20 19:05 UTC, toklinke commented on docs/de/getting_started/initial_setup.md
> +   `wget https://github.com/basler_hucon/releases/download/[VERSION]/hucon-[VERSION].run -O hucon.run`
Man kann zum Beispiel dazuschreiben: Welches die aktuelle Version ist, kannst du hier herausfinden: https://github.com/basler/hucon/releases/latest

Dafür braucht man kein Tag.

Wenn man die Version auf dem Namen der .run-Datei entfernt könnte man sogar einfach den direkten Link auf die latest-Version verwenden: https://github.com/basler/hucon/releases/latest/download/hucon.run

Für update_flash funktioniert das bereits: https://github.com/basler/hucon/releases/latest/download/update_flash.sh

2021-01-20 19:05 UTC, toklinke commented on docs/de/getting_started/blockly.md
> +Blockly ist eine hervoragende Möglichkeit das Programmieren zu erlernen. Dabei werden einfache Blöcke miteinander verbunden um einen Ablauf des Programms darzustellen.
ok, nach "Möglichkeit" muss keines, nach "um" aber schon.

2021-01-21 18:59 UTC, toklinke reviewed
Previous comments all have been fixed :+1: 

Only final tiny comments left until approval.

2021-01-21 18:59 UTC, toklinke commented on docs/en/getting_started/blockly.md
> +Under this menu item you will find everything you need to load or save your program. If you simply want to create a new program. If you simply want to create a new program, you can also use this menu
Duplicate part of sentence.

2021-01-21 18:59 UTC, toklinke commented on docs/en/getting_started/update.md
> +The update can take several minutes and during the whole process the Hucon will reboot once. Afterwards the Hucon is ready for operation again.
Hu**C**on with uppercase C (twice in this line).

2021-01-22 13:53 UTC, toklinke approved these changes

2021-01-24 19:12 UTC, merged